IF(RPM)

SET(CPACK_GENERATOR "RPM")
SET(CPACK_RPM_PACKAGE_DEBUG 1)
SET(CPACK_PACKAGING_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX})
CMAKE_MINIMUM_REQUIRED(VERSION 2.8.7)

SET(CPACK_RPM_PACKAGE_REQUIRES "unixODBC")

SET(ignored
  "%ignore ${INSTALL_LIBDIR_RPM}"
  "%ignore ${INSTALL_PCDIR_RPM}"
  )

SET(CPACK_RPM_USER_FILELIST
    ${ignored}
    )

# "set/append array" - append a set of strings, separated by a space
MACRO(SETA var)
  FOREACH(v ${ARGN})
    SET(${var} "${${var}} ${v}")
  ENDFOREACH()
ENDMACRO(SETA)

#SETA(CPACK_RPM_PACKAGE_OBSOLETES)
#SETA(CPACK_RPM_PACKAGE_PROVIDES)

MACRO(ADDIF var)
  IF(DEFINED ${var})
    SETA(CPACK_RPM_SOURCE_PKG_BUILD_PARAMS "-D${var}=${${var}}")
  ENDIF()
ENDMACRO()

ENDIF(RPM)
